/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formativeassessment.pkg3.gui.presentation;

import formativeassessment.pkg3.gui.domain.model.StudentBooking;
import formativeassessment.pkg3.gui.domain.repository.StudentBookingRepository;
import formativeassessment.pkg3.gui.util.Resource;
import formativeassessment.pkg3.gui.util.Subject;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cyabulela Shabalala
 */
public class StudentBookingUI extends javax.swing.JFrame {

    /**
     * Creates new form StudentBookingUI
     */
    
    private final StudentBookingRepository repository;
    
    public StudentBookingUI(StudentBookingRepository repository) {
        this.repository = repository;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        nameL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        surnameL = new javax.swing.JLabel();
        surnameTF = new javax.swing.JTextField();
        emailL = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        phoneL = new javax.swing.JLabel();
        phoneTF = new javax.swing.JTextField();
        subjectL = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        bookingTable = new javax.swing.JTable();
        insertBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        subjectComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.controlShadow);
        setIconImages(null);

        mainPanel.setBackground(java.awt.SystemColor.controlHighlight);

        title.setBackground(java.awt.SystemColor.controlHighlight);
        title.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Winter School Booking");

        nameL.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        nameL.setText("Name");

        surnameL.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        surnameL.setText("Surname");

        emailL.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        emailL.setText("Email");

        phoneL.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        phoneL.setText("Phone");

        subjectL.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        subjectL.setText("Subject");

        bookingTable.setAutoCreateRowSorter(true);
        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Surname", "Email", "Phone", "Subject"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bookingTable.setToolTipText("");
        bookingTable.setAutoscrolls(false);
        bookingTable.setRowSorter(null);
        bookingTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        bookingTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        scrollPane.setViewportView(bookingTable);
        bookingTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (bookingTable.getColumnModel().getColumnCount() > 0) {
            bookingTable.getColumnModel().getColumn(0).setResizable(false);
            bookingTable.getColumnModel().getColumn(1).setResizable(false);
            bookingTable.getColumnModel().getColumn(2).setResizable(false);
            bookingTable.getColumnModel().getColumn(3).setResizable(false);
            bookingTable.getColumnModel().getColumn(4).setResizable(false);
        }

        insertBtn.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 12)); // NOI18N
        insertBtn.setText("Insert");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        viewBtn.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 12)); // NOI18N
        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 12)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        subjectComboBox.setModel(new DefaultComboBoxModel(Subject.values()));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                        .addComponent(nameL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nameTF))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(subjectL))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailTF)
                                            .addComponent(subjectComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(183, 183, 183)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(surnameL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(surnameTF)
                                    .addComponent(phoneTF)))
                            .addComponent(scrollPane)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(insertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameL)
                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(surnameL)
                        .addComponent(surnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailL)
                        .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneL)))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectL)
                    .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertBtn)
                    .addComponent(viewBtn))
                .addGap(18, 18, 18)
                .addComponent(exitBtn)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        repository.closeConnection();
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        // TODO add your handling code here:
        Resource<StudentBooking> booking = getStudentBooking();
        if(booking.isSuccess()){
            Resource<StudentBooking> result = repository.insertStudentBooking(booking.getSuccess().getResult());
            if(result.isFailure()){
                showErrorMessage(result.getFailure().getReason());
            }else{
                showInfoMessage(booking.getSuccess().getResult().fName() + " has been added to the list");
            }
        }else{
            showInfoMessage(booking.getFailure().getReason());
        }
    }//GEN-LAST:event_insertBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        Resource<List<StudentBooking>> bookings = repository.getAllSudentBooking();
        if(bookings.isFailure()){
            showErrorMessage(bookings.getFailure().getReason());
            return;
        }
        DefaultTableModel model = (DefaultTableModel) bookingTable.getModel();
        //clear table
        for(int index = 0 ; index < model.getRowCount() ; index++){
            model.removeRow(index);
        }
        
        for(StudentBooking booking : bookings.getSuccess().getResult()){
            model.addRow(new Object[]{booking.fName(), booking.lName(), booking.email(), booking.phone(), booking.subject()});
        }
        model.fireTableDataChanged();
        scrollPane.revalidate();
        scrollPane.repaint();
    }//GEN-LAST:event_viewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookingTable;
    private javax.swing.JLabel emailL;
    private javax.swing.JTextField emailTF;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton insertBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel phoneL;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JComboBox<String> subjectComboBox;
    private javax.swing.JLabel subjectL;
    private javax.swing.JLabel surnameL;
    private javax.swing.JTextField surnameTF;
    private javax.swing.JLabel title;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables


    private Resource<StudentBooking> getStudentBooking() {
        if(nameTF.getText().isBlank()){ 
            return Resource.failure("Some field is blank");
        }if(surnameTF.getText().isBlank()){
            return Resource.failure("Some field is blank");
        }if(emailTF.getText().isBlank()){
            return Resource.failure("Some field is blank");
        }if(phoneTF.getText().isBlank()){
            return Resource.failure("Some field is blank");
        }if(emailTF.getText().length() > 15){
            return Resource.failure("Email too long");
        }if(nameTF.getText().length() > 10){
            return Resource.failure("Name too long"); 
        }if(surnameTF.getText().length() > 10){
            return Resource.failure("Surname too long");
        }if(phoneTF.getText().length() > 10){
            return Resource.failure("Phone number too long");
        }
        return Resource.success(
            new StudentBooking(
                nameTF.getText(),
                surnameTF.getText(),
                emailTF.getText(),
                phoneTF.getText(),
                ((Subject)subjectComboBox.getSelectedItem()).name()
            )
        );
    }
    
    private void showErrorMessage(String message) {
        JOptionPane.showMessageDialog(rootPane, message, null, JOptionPane.ERROR_MESSAGE);
    }
    
    private void showInfoMessage(String message) {
        JOptionPane.showMessageDialog(rootPane, message);
    }
}
